config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :posts do
    resources :comments
  end
    authenticate :user, lambda { |u| u.admin? } do
      mount Sidekiq::Web => '/sidekiq'
    end


  devise_for :users
  root to: 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
    has_rich_text :body
    belongs_to :user
    acts_as_punchable
    has_many :comments, dependent: :destroy

    TOPICS=["Ruby on Rails", "JavaScript", "React", "Technology", "General", "Jobs"]
end

app/models/user.rb
class User < ApplicationRecord
has_person_name

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts
  has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
      devise_parameter_sanitizer.permit(:account_update, keys: [:name])
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user! # authenticate before anyone can comment who is not logged in.
  before_action :set_comment, only: [:edit, :update, :show, :destroy]
  before_action :set_post

  def new
    @comment = Comment.new
  end

  def create
    @comment = @post.comments.create(params[:comment].permit(:reply, :post_id))
    @comment.user_id = current_user.id

    respond_to do |format|
      if @comment.save
        format.html { redirect_to post_path(@post) }
        format.js # renders create.js.erb
      else
        format.html { redirect_to post_path(@post), notice: "Your comment did not save. Please try again." }
        format.js
      end
    end
  end

  def destroy
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_to post_path(@post)
  end

  private

  def set_post
    @post = Post.find(params[:post_id])
  end

  def set_comment
    @comment = Comment.find(params[:id])
  end

  def comment_params
    params.require(:comment).permit(:reply)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: %i[ create edit update destroy ]
  # makes sure a user is logged in before creating updating and destroying
  before_action :set_post, only: %i[ show edit update destroy ]
  # Add Authenticate User for create, update, destroy ^

  # GET /posts or /posts.json
  def index
    @posts = Post.most_hit
  end

  # GET /posts/1 or /posts/1.json
  def show
    @post.punch(request)
    @comment = Comment.new
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :body, :topic, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

    def author_of(record)
        user_signed_in? && current_user.id == record.user_id
    end
    
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/comments/_comment.html.erb
<div class="flex items-start p-4 mt-4 border rounded">
    <div class="flex-1 pl-4 flex items-start justify-between">
        <div class="leading-normal">
            <p class="text-grey-700 text-xs"><%= comment.user.name %> commented <%= time_ago_in_words(comment.created_at) %> ago</p>
            <div class="text-grey-800"><%= comment.reply %></div>
        </div>

        <% if author_of(comment) %>
            <%= link_to "Delete", post_comment_path(comment.post, comment), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-red" %>
        <% end %>
    </div>
</div>

app/views/comments/_form.html.erb
<p class="text-sm text-grey-700 my-2">comment as <%= current_user.name %></p>

<%= form_for([@post, @comment], remote: true) do |f| %>
    <div class="relative">
        <%= f.text_area :reply, class: 'input h-32 border border-grey-200 p-4 resize-none', placeholder: "Comment on the blog post here..." %>

        <%= f.submit class: 'btn btn-sm btn-orange block w-full text-center mt-2 lg: mt-0 lg:text-left lg:absolute lg:pin-b lg:pin-r lg:mb-2 lg:mr-2 lg:w-auto lg:inline-flex' %>
    </div>
<% end %>

app/views/comments/create.js.erb
var comment = document.getElementById("comments");
var commentField = document.getElementById("comment_reply");

comments.insertAdjacentHTML("beforeend", "<%= escape_javascript(render(@comment)) %>");
commentField.value = "";

app/views/home/index.html.erb
<div class="max-w-lg mx-auto mt-16 text-center">
  <h1 class="mb-4 text-3xl font-black">Welcome to Kickoff Tailwind!</h1>
  <p class="text-lg leading-snug">Use this starting point as a way to quickly set up a new project by generating files, installing gems, and more.</p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="antialiased">
  <%= render "shared/head" %>

  <body class="font-sans font-normal leading-normal text-gray-800 bg-white">
    <%= render "shared/flash_notice" %>
    <%= render "shared/header" %>

    <main class="px-4 lg:px-10">
      <%= content_for?(:content) ? yield(:content) : yield %>
    </main>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="input-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: "input" %>
  </div>

  <div class="input-group">
    <%= form.label :body %>
    <%= form.rich_text_area :body, class: "input" %>
  </div>

  <div class="input-group">
    <%= form.label :topic, class: "label" %>
    <%= form.collection_select :topic, Post::TOPICS, :to_s, :to_s, class: "select py-2 px-2 mr-2" %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<div class="container m-auto my-4">
  <div class="bg-white pg-10 border rounded">
      <div id="all-posts" class="tab-panel p-5">
          <h1 class="text-xl"><strong>Posts</strong></h1>
          <% @posts.each do |post| %>
              <div class="flex flex-wrap items-center justify-start p-4 border-b-2 border-grey-100 mb-6">
                  <div class="flex-1 flex justify-between">
                      <div>
                          <%= link_to post.title, post, class: "btn-link mr-4"%>
                      </div>
                      <div>
                          <p><%= post.topic %></p>
                      </div>
                  </div>
              </div>
              <%#= link_to "Delete Post", post, method: :delete, data: { confirm: "Are you sure?"}, class: "btn btn-red ml-4" if admin? %>
          <% end %>
      </div>
  </div>
</div>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<div class="max-w-3xl my-10 m-auto">
  <div class="p-10 bg-white border border-grey-200 rounded">

    <div class="flex flex-wrap justify-between items-center mb-5">
    <h1 class="text-xl"><strong><%= @post.title %></strong></h1>
      <p class="text-sm"><strong>Email: </strong><%= @post.user.email %> | <strong>Name: </strong><%= @post.user.name %> | <strong>Views: </strong><%= @post.hits %></p>
      <%#= link_to "Delete Registration", post_path(@post), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-red" if admin? %>
    </div>

    <div class="border p-6 bg-grey-200 mb-5 items-center justify-between">
      <div class="justify-between items-center mb-5">
        <p><%= @post.body %></p>
      </div>
    </div>

    <h1 class="text-lg"><strong>Comments</strong></h1>
    <hr class="border"/>

    <div id="comments">
      <%= render @post.comments %>
    </div>
    
    <% unless user_signed_in? %>
      <div class="bg-grey-200 rounded p-4 mt-4 text-center">
        <p class="text-sm text-grey-600"><%= link_to "Login", new_user_session_path, class: "btn-link" %> or <%= link_to "Sign Up", new_user_registration_path, class: "btn-link"%> to comment.</p>
      </div>
    <% else %>
      <%= render 'comments/form' %>
    <% end %>


  </div>
  <%= link_to 'Back', posts_path %>
</div>

app/views/shared/_flash_notice.html.erb
<% flash.each do |type, message| %>
  <% if type == "alert" %>
    <div class="bg-red-500">
      <div class="container px-2 py-4 mx-auto font-sans font-medium text-center text-white"><%= message %></div>
    </div>
  <% end %>
  <% if type == "notice" %>
    <div class="bg-green-500">
      <div class="container px-2 py-4 mx-auto font-sans font-medium text-center text-white"><%= message %></div>
    </div>
  <% end %>
<% end %>

app/views/shared/_head.html.erb
 <head>
  <title>
    <% if content_for?(:title) %>
      <%= yield :title %> |
    <% end %>
    Kickoff Tailwind
  </title>

  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <meta name="viewport" content="width=device-width, initial-scale=1">

  <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_pack_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag  'application', 'data-turbolinks-track': 'reload' %>
  <%#= javascript_include_tag 'https://js.stripe.com/v3/', 'data-turbolinks-track': 'reload' %>
</head>

app/views/shared/_header.html.erb
<header class="mb-4">
  <nav class="flex flex-wrap items-center justify-between px-3 py-3 text-gray-700 bg-gray-100 lg:px-10">
    <div class="flex items-center mr-6 flex-no-shrink">
      <%= link_to "Techy Blogs", root_path, class:"link text-xl tracking-tight font-black" %>
    </div>
    <div class="block lg:hidden">
      <button class="flex items-center px-3 py-2 border border-gray-500 rounded text-grey hover:text-gray-600 hover:border-gray-600">
        <svg class="w-3 h-3 fill-current" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><title>Menu</title><path d="M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z"/></svg>
      </button>
    </div>
    <div class="items-center block w-full text-center lg:flex-1 lg:flex lg:text-left">
      <div class="lg:flex-grow">
        <%= link_to "Blogs", posts_path, class: "block mt-4 lg:inline-block lg:mt-0 lg:mr-4 mb-2 lg:mb-0 link" %>
        <% if user_signed_in? %>
          <%= link_to "Add New Post", new_post_path, class: "block mt-4 lg:inline-block lg:mt-0 lg:mr-4 mb-2 lg:mb-0 link" %>
        <% end %>
      </div>
      <div class="items-center block w-full mt-2 text-center lg:flex lg:flex-row lg:flex-1 lg:mt-0 lg:text-left lg:justify-end">
        <% if user_signed_in? %>
          <%= link_to "Edit account", edit_user_registration_path, class: "btn btn-default mb-2 lg:mr-2 lg:mb-0 block" %>
          <%= link_to "Log out", destroy_user_session_path, method: :delete, class:"btn btn-default mb-2 lg:mb-0 block" %>
        <% else %>
          <%= link_to "Login", new_user_session_path, class:"btn btn-default mb-2 lg:mr-2 lg:mb-0 block" %>
          <%= link_to "Sign Up", new_user_registration_path, class:"btn btn-default block" %>
        <% end %>
      </div>
    </div>
  </nav>
</header>